# Generated by Django 3.2 on 2021-04-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetentry',
            options={'verbose_name_plural': 'budget entries'},
        ),
        migrations.AlterModelOptions(
            name='budgetentrycategory',
            options={'verbose_name_plural': 'budget entry categories'},
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='manufacturer',
        ),
    ]
