# Generated by Django 3.2 on 2021-04-25 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='budgetentrycategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='budgetentrycategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated'),
        ),
    ]
