# Generated by Django 3.2 on 2021-04-25 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210425_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152562, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152593, tzinfo=utc), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152562, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152593, tzinfo=utc), verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='budgetentrycategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152562, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='budgetentrycategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 18, 47, 152593, tzinfo=utc), verbose_name='Updated'),
        ),
    ]
